window.SHOWCASE_PROJECTS = [
  { title: 'AI portfolio and resume website', status: 'Live', purpose: 'The professional showcase layer for Joel\'s IT experience and AI-assisted development work.', usefulFor: 'Recruiters and technical teams reviewing practical capability.', tech: ['HTML', 'CSS', 'JavaScript', 'GitHub Pages'], ai: 'AI-assisted planning, coding and review with human validation.', contribution: 'Designed the content model, structure and deployment workflow; verified the published site.', testing: 'Responsive, local preview and live HTTP checks.', limitations: 'Case studies will expand as the separate tools become reliable.', links: [['Live site', 'https://jlbrucehelpful-hash.github.io/joel-resume/'], ['Source', 'https://github.com/jlbrucehelpful-hash/joel-resume']] },
  { title: 'Transcription Lab', status: 'Planned', purpose: 'A privacy-conscious local tool for useful, timestamped transcripts and summaries.', usefulFor: 'People who need searchable notes from recordings without sending audio to a hosted service.', tech: ['Python', 'Whisper', 'Audio processing'], ai: 'Whisper Large V3 Turbo and AI-assisted workflow design.', contribution: 'Planned the local workflow, output formats and validation approach.', testing: 'To be tested with representative, sanitised audio and clean-install instructions.', limitations: 'Not yet ready for public use; performance and packaging remain to be validated.', links: [] },
  { title: 'Endpoint Automation Toolkit', status: 'In development', purpose: 'PowerShell checks and reports for common Windows endpoint health and support tasks.', usefulFor: 'Service desk and endpoint teams needing repeatable health checks.', tech: ['PowerShell', 'Windows', 'CSV reporting'], ai: 'AI-assisted scripting, test-case design and documentation review.', contribution: 'Applying enterprise Desktop Support experience to safe, useful checks and support-friendly output.', testing: 'Each check will be tested against expected endpoint states.', limitations: 'The first version will remain small and will not integrate with enterprise policy systems.', links: [] },
  { title: 'Helpdesk AI Workflow', status: 'Planned', purpose: 'A structured workflow for turning technical notes into support responses, knowledge articles and escalation summaries.', usefulFor: 'Service desks improving consistency, handover quality and knowledge reuse.', tech: ['Structured prompts', 'Markdown', 'Workflow automation'], ai: 'LLM-assisted drafting with human review and fact checking.', contribution: 'Applying ITIL-aligned incident ownership and escalation experience to the workflow design.', testing: 'Sanitised support scenarios and defined acceptance criteria.', limitations: 'AI output requires human approval; confidential ticket data will not be used.', links: [] },
  { title: 'Document Action Pipeline', status: 'Planned', purpose: 'A tool concept for converting notes or transcripts into decisions, owners, deadlines and follow-up actions.', usefulFor: 'Teams needing structure from unstructured workplace information.', tech: ['Document processing', 'Structured data', 'Automation'], ai: 'AI-assisted extraction, validation and iteration.', contribution: 'Defining practical outputs and verification steps around workplace coordination needs.', testing: 'Planned comparison against known, sanitised examples.', limitations: 'Not yet implemented; ambiguous ownership and dates need explicit handling.', links: [] },
  { title: 'Small Business Workflow App', status: 'Planned', purpose: 'A lightweight workflow for enquiries, job intake, task status, checklists and completion summaries.', usefulFor: 'Small teams needing a clear operational record without a large platform rollout.', tech: ['Web application', 'Forms', 'Status tracking'], ai: 'AI-assisted requirements breakdown and usability iteration where appropriate.', contribution: 'Shaping a practical, user-focused workflow with clear boundaries.', testing: 'Planned scenario testing from intake through completion.', limitations: 'A prototype would not replace a production CRM or continuity system.', links: [] },
  { title: 'Project Validation Dashboard', status: 'Planned', purpose: 'A simple view of tests, documentation, deployment status, known issues and release readiness.', usefulFor: 'Small teams wanting visible evidence before publishing a tool.', tech: ['HTML', 'JavaScript', 'Release checks'], ai: 'AI-assisted checklist design with human verification.', contribution: 'Applying an evidence-first approach to testing, documentation and deployment decisions.', testing: 'The dashboard will be checked against project release scenarios.', limitations: 'It reports evidence; it does not replace full CI/CD or test management platforms.', links: [] },
  { title: 'Packaged Windows Utility', status: 'Future', purpose: 'A downloadable Windows application based on the strongest validated portfolio utility.', usefulFor: 'Users who need a straightforward installable tool rather than a prototype.', tech: ['Windows packaging', 'Desktop utility', 'Installer'], ai: 'AI-assisted packaging research, documentation and testing support.', contribution: 'Selecting a proven project and defining a safe, documented user experience.', testing: 'Clean-machine installation and core workflow testing required before release.', limitations: 'Packaging waits until a project is stable and its privacy model is clear.', links: [] }
];
